apiVersion: v1
kind: Service
metadata: 
  name: conversaotemperatura
spec:
  selector:
    app: conversaotemperatura
  ports:
   - port: 8080
     protocol: TCP
     name: ui
     nodePort: 30000
  type: NodePort
  #type: ClusterIP
 